version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: campusevents_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: campus
      POSTGRES_PASSWORD: campus123
      POSTGRES_DB: campusevents
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
